#!/bin/bash

ID=$(id -u)
TIMESTAMP=$(date +%F-%H-%M-%S)

R="\e[31m" #colore coe for red
G="\e[32m" #colore coe for green
Y="\e[33m" #colore coe for yellow
N="\e[0m" #colore coe for normal

LOGFILE="/tmp/$0-$TIMESTAMP" #$0 pulles scrit file name

VALIDATE(){
    if [ $1 -eq 0 ] #$? outputs scuess or failure, scuess=0, failure=other than zero value
    then
        echo -e "$2 $G Sucuessfully! $N" #-e enables colors
    else
        echo -e "$2 $R Failed  $N"
    fi

}

if [ $ID -eq 0 ]
then
    echo "Proceeding with installtion"
else 
    echo "Run script as ROOT USER"
    exit 1 # exit command exits the script when scrit run fails
fi

yum install mysql -y &>> $LOGFILE #&>> commend appends logs to same file
VALIDATE $? "MySql installed"
yum install git -y &>> $LOGFILE
VALIDATE $? "Git installed"